version: "3.8"
services:
  mongodb:
    image: "mongo:4.4.3-bionic"
    container_name: mongodb
    environment:
    - PUID=1000
    - PGID=1000
    volumes:
    - /path/to/storage/db:/data/db
    ports:
    - 27017:27017
    restart: unless-stopped
  redis_cache:
    image: "redis:6.0.10-buster"
    container_name: redis_cache
    ports:
    - 6379:6379
    restart: unless-stopped
